Repository muktihari/fit, pull requests merged in 2024-09, with the labels that each got.

#390 fix: encoder WriteSeeker now relative to current offset
  encoder/encoder.go
  encoder/encoder_test.go
Labels: bug

#391 docs: update usage.md
  docs/usage.md
Labels: documentation

#392 docs: update usage.md
  docs/usage.md
Labels: documentation

#398 cli: refactor fitactivity
  cmd/fitactivity/README.md
  cmd/fitactivity/combiner/combiner.go
  cmd/fitactivity/combiner/combiner_test.go
  cmd/fitactivity/concealer/concealer.go
  cmd/fitactivity/main.go
  cmd/fitactivity/opener/opener.go
  cmd/fitactivity/reducer/reducer.go
  cmd/fitactivity/reducer/reducer_test.go
  go.mod
  go.sum
Labels: enhancement

#399 cli: fitactivity add message remover
  cmd/fitactivity/README.md
  cmd/fitactivity/aggregator/aggregator_test.go
  cmd/fitactivity/main.go
  cmd/fitactivity/remover/remover.go
  cmd/fitactivity/remover/remover_test.go
Labels: enhancement

#400 cli: fitactivity fix remover
  cmd/fitactivity/main.go
  cmd/fitactivity/remover/remover_test.go
Labels: bug

#401 chore: add missing copyright header
  cmd/fitactivity/remover/remover.go
  cmd/fitactivity/remover/remover_test.go
Labels: chore

#402 chore: fix misspelled words
  cmd/fitactivity/README.md
  cmd/fitactivity/combiner/combiner.go
  cmd/fitactivity/main.go
  cmd/fitactivity/reducer/reducer.go
Labels: chore

#403 chore: update CI jobs to check misspelled words
  .github/workflows/ci.yml
Labels: chore

#404 chore: update fitactivity README.md
  cmd/fitactivity/README.md
Labels: chore, cli

#405 fix: aggregator to handle enhanced fields
  cmd/fitactivity/README.md
  cmd/fitactivity/aggregator/aggregator.go
  cmd/fitactivity/aggregator/aggregator_test.go
Labels: bug, cli

#406 chore: pin misspell hash in ci workflow for security reason
  .github/workflows/ci.yml
Labels: chore

#407 chore: update dependabot interval from daily to weekly
  .github/dependabot.yml
Labels: chore

#408 fix: decoder should expand component only from a valid value
  decoder/decoder.go
  decoder/decoder_test.go
Labels: bug

#409 chore: clean up decoder code
  decoder/decoder.go
Labels: chore

#410 docs: update README.md
  README.md
  cmd/fitactivity/README.md
Labels: documentation

#411 cli: fitactivity improve concealer
  cmd/fitactivity/README.md
  cmd/fitactivity/concealer/conceal_test.go
  cmd/fitactivity/concealer/concealer.go
  cmd/fitactivity/main.go
Labels: enhancement

#412 cli: fitactivity opener limit concurrent process
  cmd/fitactivity/main.go
  cmd/fitactivity/opener/opener.go
  cmd/fitactivity/opener/opener_test.go
Labels: enhancement, cli

#413 chore: fitactivity fix typo
  cmd/fitactivity/aggregator/aggregator.go
Labels: chore

#414 feat: fitactivity implement context propagation
  cmd/fitactivity/main.go
  cmd/fitactivity/opener/opener.go
  cmd/fitactivity/opener/opener_test.go
Labels: enhancement

#415 perf: optimize encoder buffer size
  encoder/encoder.go
Labels: performance

#416 perf: round encoder buffer size to nearest sizeclasses
  encoder/encoder.go
Labels: performance

#418 refactor!: remove not particularly useful features
  cmd/fitactivity/README.md
  cmd/fitactivity/main.go
  cmd/fitprint/printer/printer.go
  decoder/accumulator.go
  decoder/accumulator_test.go
  decoder/decoder.go
  decoder/decoder_test.go
  decoder/raw.go
  decoder/raw_test.go
  docs/usage.md
  encoder/encoder.go
  encoder/encoder_bench_test.go
  encoder/encoder_test.go
  encoder/stream_test.go
  encoder/validator.go
  encoder/validator_test.go
  factory/exported_gen.go
  factory/factory_gen.go
  fuzz_test.go
  internal/cmd/benchfit/go.mod
  internal/cmd/benchfit/go.sum
  internal/cmd/fitgen/factory/factory.tmpl
  internal/cmd/testgen/big_activity.go
  internal/cmd/testgen/main.go
  internal/kit/kit.go
  internal/kit/kit_test.go
  profile/basetype/basetype.go
  profile/basetype/basetype_test.go
  profile/filedef/activity_summary_test.go
  profile/filedef/activity_test.go
  profile/filedef/blood_pressure_test.go
  profile/filedef/course_test.go
  profile/filedef/device_test.go
  profile/filedef/filedef_test.go
  profile/filedef/goals_test.go
  profile/filedef/listener_test.go
  profile/filedef/monitoring_ab_test.go
  profile/filedef/monitoring_daily_test.go
  profile/filedef/schedules_test.go
  profile/filedef/segment_list_test.go
  profile/filedef/segment_test.go
  profile/filedef/settings_test.go
  profile/filedef/sport_test.go
  profile/filedef/totals_test.go
  profile/filedef/weight_test.go
  profile/filedef/workout_test.go
  profile/mesgdef/mesgdef.go
  profile/mesgdef/mesgdef_test.go
  profile/mesgdef/record_gen_test.go
  proto/proto.go
  proto/proto_internal_test.go
  proto/proto_marshal.go
  proto/proto_marshal_test.go
  proto/proto_test.go
  proto/value_marshal.go
  proto/value_marshal_test.go
  proto/value_unmarshal.go
  proto/version.go
  proto/version_test.go
Labels: enhancement

#419 feat: filedef add new messages in Activity File
  profile/filedef/activity.go
  profile/filedef/activity_test.go
Labels: enhancement

#420 refactor: set minimal go version to v1.21
  cmd/fitactivity/combiner/combiner.go
  cmd/fitactivity/combiner/combiner_test.go
  go.mod
  go.sum
  internal/cmd/benchfit/go.mod
  internal/cmd/fitgen/pkg/flagutil/flagutil.go
  internal/cmd/fitgen/pkg/strutil/strutil_test.go
  internal/cmd/fitgen/profile/mesgdef/builder.go
  internal/cmd/fitgen/profile/untyped/fieldnum/builder.go
  kit/scaleoffset/scaleoffset.go
  profile/filedef/activity_test.go
  profile/filedef/filedef.go
Labels: enhancement

#422 chore: create FUNDING.yml
  .github/FUNDING.yml
Labels: chore

#423 chore: accumulator fix typo on code docs
  decoder/accumulator.go
Labels: chore

#424 chore: inline accumulator code
  decoder/accumulator.go
Labels: chore

#426 chore: run go mod tidy on benchfit
  internal/cmd/benchfit/go.mod
  internal/cmd/benchfit/go.sum
Labels: chore

#427 chore: clean up mesgdef builder
  internal/cmd/fitgen/profile/mesgdef/builder.go
Labels: chore

#428 refactor!: decoder sentinel errors
  decoder/decoder.go
  decoder/decoder_test.go
Labels: enhancement

#429 chore: fitactivity simplify notify signal
  cmd/fitactivity/main.go
Labels: chore

#431 chore: add missing copyright header
  profile/typedef/bool.go
  profile/typedef/bool_test.go
Labels: chore

#432 fix: encoder only compress timestamp when value is valid
  encoder/encoder.go
Labels: bug

#433 chore: add base comment for mesgdef and typedef having uintz type
  internal/cmd/fitgen/profile/mesgdef/builder.go
  internal/cmd/fitgen/profile/typedef/builder.go
  internal/cmd/fitgen/shared/constant.tmpl
  internal/cmd/fitgen/shared/constant_data.go
  profile/mesgdef/ant_channel_id_gen.go
  profile/mesgdef/bike_profile_gen.go
  profile/mesgdef/capabilities_gen.go
  profile/mesgdef/course_gen.go
  profile/mesgdef/device_info_gen.go
  profile/mesgdef/event_gen.go
  profile/mesgdef/file_capabilities_gen.go
  profile/mesgdef/file_id_gen.go
  profile/mesgdef/hrm_profile_gen.go
  profile/mesgdef/memo_glob_gen.go
  profile/mesgdef/schedule_gen.go
  profile/mesgdef/sdm_profile_gen.go
  profile/mesgdef/tank_summary_gen.go
  profile/mesgdef/tank_update_gen.go
  profile/mesgdef/training_file_gen.go
  profile/mesgdef/workout_gen.go
  profile/typedef/ant_channel_id_gen.go
  profile/typedef/connectivity_capabilities_gen.go
  profile/typedef/course_capabilities_gen.go
  profile/typedef/file_flags_gen.go
  profile/typedef/language_bits_0_gen.go
  profile/typedef/language_bits_1_gen.go
  profile/typedef/language_bits_2_gen.go
  profile/typedef/language_bits_3_gen.go
  profile/typedef/language_bits_4_gen.go
  profile/typedef/sport_bits_0_gen.go
  profile/typedef/sport_bits_1_gen.go
  profile/typedef/sport_bits_2_gen.go
  profile/typedef/sport_bits_3_gen.go
  profile/typedef/sport_bits_4_gen.go
  profile/typedef/sport_bits_5_gen.go
  profile/typedef/sport_bits_6_gen.go
  profile/typedef/supported_exd_screen_layouts_gen.go
  profile/typedef/workout_capabilities_gen.go
Labels: chore

#434 chore: decoder update code docs
  decoder/decoder.go
Labels: chore

#435 chore: clean up proto Value code
  proto/value.go
  proto/value_marshal.go
Labels: chore

#436 fix: proto UnmarshalValue on handling string padding
  proto/value_unmarshal.go
  proto/value_unmarshal_internal_test.go
  proto/value_unmarshal_test.go
Labels: bug

#438 fix: handle compressed timestamp
  decoder/decoder.go
  decoder/decoder_test.go
  decoder/raw.go
  encoder/encoder.go
  encoder/encoder_test.go
Labels: bug

#439 feat!: encoder compress timestamp with multiple local message type
  cmd/fitactivity/main.go
  cmd/fitconv/fitcsv/csv_to_fit.go
  encoder/encoder.go
  encoder/encoder_bench_test.go
  encoder/encoder_test.go
Labels: enhancement

#440 cli: fitactivity enable compressed timestamp header with multiple local message type
  cmd/fitactivity/README.md
  cmd/fitactivity/main.go
Labels: cli

#441 docs: update encoder code docs and docs/usage.md
  docs/usage.md
  encoder/encoder.go
Labels: documentation

#442 fix: decoder PeekFileId must check only the first message
  decoder/decoder.go
  decoder/decoder_test.go
Labels: bug

#443 cli: update fitactivity
  cmd/fitactivity/main.go
Labels: chore

#445 chore: update fitactivity README.md
  cmd/fitactivity/README.md
Labels: chore, cli

#446 chore: proto.UnmarshalValue simplify utf8 string decoding
  proto/value_unmarshal.go
  proto/value_unmarshal_internal_test.go
Labels: chore

#447 fix: encoder validator now print value on size error
  encoder/validator.go
Labels: bug

#448 cli: fitactivity fix combine usage
  cmd/fitactivity/main.go
Labels: chore, cli

#449 fix!: protocol validator export protocol version field
  encoder/encoder.go
  encoder/encoder_test.go
  proto/validator.go
  proto/validator_test.go
Labels: enhancement

#450 fix: typo on fitactivity conceal docs
  cmd/fitactivity/README.md
  cmd/fitactivity/main.go
Labels: chore, cli

#451 cli: fitactivity feat support combine multi-sessions
  cmd/fitactivity/README.md
  cmd/fitactivity/combiner/combiner.go
  cmd/fitactivity/combiner/combiner_test.go
Labels: enhancement, cli

#453 fix: fitactivity combine should accumulate all the accumulable values
  cmd/fitactivity/README.md
  cmd/fitactivity/combiner/accumulator.go
  cmd/fitactivity/combiner/accumulator_test.go
  cmd/fitactivity/combiner/combiner.go
  cmd/fitactivity/combiner/combiner_test.go
  cmd/fitactivity/main.go
Labels: bug, cli

#454 perf: early validate all messages before encoding
  encoder/encoder.go
  encoder/encoder_test.go
  encoder/stream.go
  encoder/stream_test.go
  encoder/validator_test.go
  proto/validator.go
  proto/validator_test.go
Labels: performance

#455 cli-fix: fitconv remove quote char and unprintable chars in csv
  cmd/fitconv/fitcsv/csv_to_fit.go
  cmd/fitconv/fitcsv/formatter.go
Labels: bug, cli

#456 cli-feat: fitconv ability to convert unknown data from CSV to FIT
  cmd/fitconv/README.md
  cmd/fitconv/fitcsv/csv_to_fit.go
  cmd/fitconv/fitcsv/fit_to_csv.go
  cmd/fitconv/main.go
Labels: enhancement, cli

#457 feat: filedef listener add ability to reset
  profile/filedef/listener.go
  profile/filedef/listener_test.go
Labels: enhancement

#458 chore: encoder clean up unused variable
  encoder/encoder_test.go
Labels: chore

#459 docs: update fitconv README.md
  cmd/fitconv/README.md
Labels: documentation

#460 fix: decoder should clear the pointers before reslicing
  decoder/decoder.go
Labels: bug

#461 cli-fix: fitconv csv-to-fit on parsing fields
  cmd/fitconv/fitcsv/csv_to_fit.go
Labels: bug, cli

#462 cli-fix: fitconv csv-to-fit on parsing fields
  cmd/fitconv/fitcsv/csv_to_fit.go
Labels: bug, cli

#463 docs: update README.md
  README.md
Labels: documentation

#464 feat: filedef activity file add sports and update its sorting
  profile/filedef/activity.go
  profile/filedef/activity_test.go
Labels: enhancement

#465 chore: filedef listener simplify code
  profile/filedef/listener.go
Labels: chore

#467 fix: decoder peek file_id
  decoder/decoder.go
  decoder/decoder_test.go
Labels: bug

#469 fix: activity file sort most messages since they now may have timestamp
  profile/filedef/activity.go
Labels: bug

#470 fix: segment file can have multiple leaderboard entries
  profile/filedef/segment.go
Labels: bug, enhancement
